### ISSUE TITLE
Define statusKey property to avoid PHP 8.2 deprecated warning

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_ui#18]
`EntityDefaultUIController` uses `statusKey` as a dynamic property. This generates warnings in PHP 8.2. The solution is to declare it as a protected property, like `entityType` etc. 

This is exactly how this problem got [fixed](https://git.drupalcode.org/project/entity/-/blob/7.x-1.x/includes/entity.ui.inc#L19) in D7 4 months ago.

**Comment by argiepiano** [comment]
PR ready for review.

**Comment by argiepiano** [comment]
I encountered this problem again when working with Organic Groups. See https://github.com/backdrop-contrib/og/issues/148

@docwilmot, this is a pretty trivial change. Unless you have any objections, I'll merge and do a new release.

**Comment by docwilmot** [comment]
No objections
