### ISSUE TITLE
Warnings during entity_plus 1.0.8 update

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/entity_ui#4]
While updating entity_plus to 1.0.8, the following warning messages were displayed:

Notice: Constant ENTITY_CUSTOM already defined in include_once() (line 10 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_IN_DB already defined in include_once() (line 15 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_IN_CODE already defined in include_once() (line 20 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_OVERRIDDEN already defined in include_once() (line 27 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_FIXED already defined in include_once() (line 33 of /backdrop/modules/entity_ui/entity_ui.module).

....and after running database updates:

Notice: Constant ENTITY_CUSTOM already defined in include_once() (line 10 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_IN_DB already defined in include_once() (line 15 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_IN_CODE already defined in include_once() (line 20 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_OVERRIDDEN already defined in include_once() (line 27 of /backdrop/modules/entity_ui/entity_ui.module).
Notice: Constant ENTITY_FIXED already defined in include_once() (line 33 of /backdrop/modules/entity_ui/entity_ui.module).
Warning: Invalid argument supplied for foreach() in path_entity_load() (line 421 of /backdrop/core/modules/path/path.module)

The site is running on:

Debian 10.5
PHP 7.3.19-1~deb10u1
MariaDB  Ver 15.1 Distrib 10.3.23-MariaDB

**Comment by laryn** [comment]
@and-e-h It's a little dirty but for a temporary fix until we figure out how to handle this, can you test this?

 - https://github.com/backdrop-contrib/entity_plus/issues/20#issuecomment-692016656

**Comment by oadaeh** [comment]
I think something similar to what went into Entity Plus should also go into Entity UI.

**Comment by and-e-h** [comment]
@laryn Apologies for the delay in responding, but that fix does the trick! Thanks! :)

**Comment by olafgrabienski** [comment]
I'm currently testing @laryn's [port of Organic Groups](https://github.com/laryn/og) which requires Entity UI and Entity Plus. After enabling the latest releases of the Entity modules, I got the mentioned PHP notices on the page `admin/installer/install`, although Entity Plus 1.x-1.0.10 in my understanding should have fixed the issue.

However, when I went to `admin/installer/install` again, the messages didn't appear again.

For reference, the messages I saw:

- Notice: Constant ENTITY_CUSTOM already defined in include_once() (line 10 of .../modules/entity_ui/entity_ui.module).
- Notice: Constant ENTITY_IN_DB already defined in include_once() (line 15 of .../modules/entity_ui/entity_ui.module).
- Notice: Constant ENTITY_IN_CODE already defined in include_once() (line 20 of .../modules/entity_ui/entity_ui.module).
- Notice: Constant ENTITY_OVERRIDDEN already defined in include_once() (line 27 of .../modules/entity_ui/entity_ui.module).
- Notice: Constant ENTITY_FIXED already defined in include_once() (line 33 of .../modules/entity_ui/entity_ui.module).

**Comment by argiepiano** [comment]
Closing this, as this problem has been fixed in Entity Plus by renaming the constants to avoid collisions.
