### ISSUE TITLE
entity_ui_access is always TRUE, access callback is wrong for content entities ui controller 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_ui#5]
Currently function `entity_ui_access` always returns TRUE, effectively allowing ANYONE (even anonymous users) to access the admin ui for any operation on content and configuration entities.

Additionally, the access callback used for the menu items created in `hook_menu` in  classes `EntityContentUIController` and `EntityBundleableUIController`  wrongly use `entity_ui_access` as their access callback. Since these two classes are used to provide UIs for content and bundeable entities, they should instead use core's `entity_access`, as those menu items are used to create, edit or delete "regular" content entities (rather than configuration entities).

**Comment by rbargerhuff** [comment]
We are in a situation where we are porting all our Drupal 7 code base  with regards to custom modules to Backdrop CMS. We noticed that entity_ui_access is literally allowing anyone (Anonymous!) to access admin UIs that implement entity_ui.

This is a major security concern. Why has this not been addressed by acceptance of the pull request?

**Comment by argiepiano** [comment]
I recently became maintainer of this module (after my original report). I'll work on getting this fixed ASAP

**Comment by argiepiano** [comment]
I have changed the approach slightly by rewriting `entity_ui_access()`. This function now uses the `access callback` defined in `hook_entity_info()`. I mean: `access callback` present at the root level of the array returned by `hook_entity_info()`, which was actually removed from Backdrop's  entity definition, and therefore is not used in Backdrop's `entity_access()`.

Therefore, for backward compatibility with modules that used Entity API in D7, I am providing `entity_ui_access()` that checks `access callback` (since this key WILL be present in ported modules that used D7 Entity API).  If that key is not present, then the access check falls back to Backdrop's `entity_access()`. 

@rbargerhuff can you please test this in your installations/modules? I've done testing with custom entities that use Entity Plus and the access checks are now working correctly. 

I will merge this into the dev version of the module to facilitate testing. 

@docwilmot, I'm not sure if you are still interested in co-maintaining? If so, would you please take a look as well?

**Comment by argiepiano** [comment]
PR #12

**Comment by argiepiano** [comment]
Actually I can't merge. Although I'm listed as a maintainer [here](https://backdropcms.org/project/entity_ui) I don't have write access 👎🏽

**Comment by argiepiano** [comment]
PR now has been merged. I'll reopen this until the dev version has been tested

**Comment by rbargerhuff** [comment]
@argiepiano Great work on getting this updated and committed. My colleague and I have tested the code changes and as far as we can tell, everything works as it should. Friday evening, anonymous could access our admin page. And with your code changes, this was prevented. Like I said, as far as we can tell, and as far as our testing can allow us to go, these code changes were successful.

From what we can tell, Backdrop has removed `access_callback()` definition from the entity definition in hook_entity_info() in favor of overriding the `access()` method that is defined within the entity class.

In our opinion, the 'access callback' definition should be moved inside the `admin ui` definition since `access callback()` is no longer applies to the top level. Unfortunately this would break any `entity_ui` use within a Drupal 7 migration. So perhaps this should be a long term consideration.

**Comment by argiepiano** [comment]
Thanks for testing, @rbargerhuff! 

> In our opinion, the 'access callback' definition should be moved inside the admin ui definition since access callback() is no longer applies to the top level

While `access callback` was removed from core entity handling, Entity Plus (which is a partial port of Entity API) still uses the `access callback` definition to check access.  Moving `'access callback'` within `'admin ui'` would break this as well. 

Even though Entity UI and Entity Plus were split up in Backdrop, they are still quite integrated (it's rare for someone to use Entity UI and not Entity Plus). There's been some talk on Zulip about merging these two back.

**Comment by argiepiano** [comment]
Closing this one since it's been tested.
