### ISSUE TITLE
Offer to become co-maintainer of Entity UI

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_ui#9]
Hello @docwilmot. I wanted to offer to co-maintain this module. 

I'm already co-maintaining Entity Plus and Entity Tokens, and collaborating closely with Rules and Ubercart, so I thought it would make sense to also help co-maintain Entity UI. 

Please let me know if you are open to that. Thanks!

**Comment by docwilmot** [comment]
By all means, welcome. Send the PR when you're ready to add you to README. Thanks.

**Comment by argiepiano** [comment]
Thanks! Just added PR #10 .

BTW, there are a couple of issues and PRs I created a few months ago here - I probably need to review/revise those.
